// Code generated by go-swagger; DO NOT EDIT.

// /**
//  * OpenPSD PSD2 Server
//  * 2018 - OpenPSD - openpsd.org
//  * Released under the GNU General Public License
//  */

package funds

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/openpsd/psd2-server/models"
)

// FundsConfirmationsPostOKCode is the HTTP code returned for type FundsConfirmationsPostOK
const FundsConfirmationsPostOKCode int = 200

/*FundsConfirmationsPostOK OK

swagger:response fundsConfirmationsPostOK
*/
type FundsConfirmationsPostOK struct {

	/*
	  In: Body
	*/
	Payload *models.FundsConfirmationsResponse `json:"body,omitempty"`
}

// NewFundsConfirmationsPostOK creates FundsConfirmationsPostOK with default headers values
func NewFundsConfirmationsPostOK() *FundsConfirmationsPostOK {

	return &FundsConfirmationsPostOK{}
}

// WithPayload adds the payload to the funds confirmations post o k response
func (o *FundsConfirmationsPostOK) WithPayload(payload *models.FundsConfirmationsResponse) *FundsConfirmationsPostOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the funds confirmations post o k response
func (o *FundsConfirmationsPostOK) SetPayload(payload *models.FundsConfirmationsResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FundsConfirmationsPostOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// FundsConfirmationsPostBadRequestCode is the HTTP code returned for type FundsConfirmationsPostBadRequest
const FundsConfirmationsPostBadRequestCode int = 400

/*FundsConfirmationsPostBadRequest Bad Request

swagger:response fundsConfirmationsPostBadRequest
*/
type FundsConfirmationsPostBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.TppMessage `json:"body,omitempty"`
}

// NewFundsConfirmationsPostBadRequest creates FundsConfirmationsPostBadRequest with default headers values
func NewFundsConfirmationsPostBadRequest() *FundsConfirmationsPostBadRequest {

	return &FundsConfirmationsPostBadRequest{}
}

// WithPayload adds the payload to the funds confirmations post bad request response
func (o *FundsConfirmationsPostBadRequest) WithPayload(payload *models.TppMessage) *FundsConfirmationsPostBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the funds confirmations post bad request response
func (o *FundsConfirmationsPostBadRequest) SetPayload(payload *models.TppMessage) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FundsConfirmationsPostBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// FundsConfirmationsPostUnauthorizedCode is the HTTP code returned for type FundsConfirmationsPostUnauthorized
const FundsConfirmationsPostUnauthorizedCode int = 401

/*FundsConfirmationsPostUnauthorized Unauthorized

swagger:response fundsConfirmationsPostUnauthorized
*/
type FundsConfirmationsPostUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.TppMessage `json:"body,omitempty"`
}

// NewFundsConfirmationsPostUnauthorized creates FundsConfirmationsPostUnauthorized with default headers values
func NewFundsConfirmationsPostUnauthorized() *FundsConfirmationsPostUnauthorized {

	return &FundsConfirmationsPostUnauthorized{}
}

// WithPayload adds the payload to the funds confirmations post unauthorized response
func (o *FundsConfirmationsPostUnauthorized) WithPayload(payload *models.TppMessage) *FundsConfirmationsPostUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the funds confirmations post unauthorized response
func (o *FundsConfirmationsPostUnauthorized) SetPayload(payload *models.TppMessage) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FundsConfirmationsPostUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// FundsConfirmationsPostForbiddenCode is the HTTP code returned for type FundsConfirmationsPostForbidden
const FundsConfirmationsPostForbiddenCode int = 403

/*FundsConfirmationsPostForbidden Forbidden

swagger:response fundsConfirmationsPostForbidden
*/
type FundsConfirmationsPostForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.TppMessage `json:"body,omitempty"`
}

// NewFundsConfirmationsPostForbidden creates FundsConfirmationsPostForbidden with default headers values
func NewFundsConfirmationsPostForbidden() *FundsConfirmationsPostForbidden {

	return &FundsConfirmationsPostForbidden{}
}

// WithPayload adds the payload to the funds confirmations post forbidden response
func (o *FundsConfirmationsPostForbidden) WithPayload(payload *models.TppMessage) *FundsConfirmationsPostForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the funds confirmations post forbidden response
func (o *FundsConfirmationsPostForbidden) SetPayload(payload *models.TppMessage) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FundsConfirmationsPostForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*FundsConfirmationsPostDefault Internal Server Error

swagger:response fundsConfirmationsPostDefault
*/
type FundsConfirmationsPostDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.TppMessage `json:"body,omitempty"`
}

// NewFundsConfirmationsPostDefault creates FundsConfirmationsPostDefault with default headers values
func NewFundsConfirmationsPostDefault(code int) *FundsConfirmationsPostDefault {
	if code <= 0 {
		code = 500
	}

	return &FundsConfirmationsPostDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the funds confirmations post default response
func (o *FundsConfirmationsPostDefault) WithStatusCode(code int) *FundsConfirmationsPostDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the funds confirmations post default response
func (o *FundsConfirmationsPostDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the funds confirmations post default response
func (o *FundsConfirmationsPostDefault) WithPayload(payload *models.TppMessage) *FundsConfirmationsPostDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the funds confirmations post default response
func (o *FundsConfirmationsPostDefault) SetPayload(payload *models.TppMessage) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FundsConfirmationsPostDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
