// Code generated by go-swagger; DO NOT EDIT.

// /**
//  * OpenPSD PSD2 Server
//  * 2018 - OpenPSD - openpsd.org
//  * Released under the GNU General Public License
//  */

package account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/openpsd/psd2-server/models"
)

// AccountsByAccountIDGetOKCode is the HTTP code returned for type AccountsByAccountIDGetOK
const AccountsByAccountIDGetOKCode int = 200

/*AccountsByAccountIDGetOK OK

swagger:response accountsByAccountIdGetOK
*/
type AccountsByAccountIDGetOK struct {

	/*
	  In: Body
	*/
	Payload *models.AccountsResponse18 `json:"body,omitempty"`
}

// NewAccountsByAccountIDGetOK creates AccountsByAccountIDGetOK with default headers values
func NewAccountsByAccountIDGetOK() *AccountsByAccountIDGetOK {

	return &AccountsByAccountIDGetOK{}
}

// WithPayload adds the payload to the accounts by account Id get o k response
func (o *AccountsByAccountIDGetOK) WithPayload(payload *models.AccountsResponse18) *AccountsByAccountIDGetOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the accounts by account Id get o k response
func (o *AccountsByAccountIDGetOK) SetPayload(payload *models.AccountsResponse18) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AccountsByAccountIDGetOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// AccountsByAccountIDGetBadRequestCode is the HTTP code returned for type AccountsByAccountIDGetBadRequest
const AccountsByAccountIDGetBadRequestCode int = 400

/*AccountsByAccountIDGetBadRequest Bad Request

swagger:response accountsByAccountIdGetBadRequest
*/
type AccountsByAccountIDGetBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.TppMessage `json:"body,omitempty"`
}

// NewAccountsByAccountIDGetBadRequest creates AccountsByAccountIDGetBadRequest with default headers values
func NewAccountsByAccountIDGetBadRequest() *AccountsByAccountIDGetBadRequest {

	return &AccountsByAccountIDGetBadRequest{}
}

// WithPayload adds the payload to the accounts by account Id get bad request response
func (o *AccountsByAccountIDGetBadRequest) WithPayload(payload *models.TppMessage) *AccountsByAccountIDGetBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the accounts by account Id get bad request response
func (o *AccountsByAccountIDGetBadRequest) SetPayload(payload *models.TppMessage) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AccountsByAccountIDGetBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// AccountsByAccountIDGetUnauthorizedCode is the HTTP code returned for type AccountsByAccountIDGetUnauthorized
const AccountsByAccountIDGetUnauthorizedCode int = 401

/*AccountsByAccountIDGetUnauthorized Unauthorized

swagger:response accountsByAccountIdGetUnauthorized
*/
type AccountsByAccountIDGetUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.TppMessage `json:"body,omitempty"`
}

// NewAccountsByAccountIDGetUnauthorized creates AccountsByAccountIDGetUnauthorized with default headers values
func NewAccountsByAccountIDGetUnauthorized() *AccountsByAccountIDGetUnauthorized {

	return &AccountsByAccountIDGetUnauthorized{}
}

// WithPayload adds the payload to the accounts by account Id get unauthorized response
func (o *AccountsByAccountIDGetUnauthorized) WithPayload(payload *models.TppMessage) *AccountsByAccountIDGetUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the accounts by account Id get unauthorized response
func (o *AccountsByAccountIDGetUnauthorized) SetPayload(payload *models.TppMessage) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AccountsByAccountIDGetUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// AccountsByAccountIDGetForbiddenCode is the HTTP code returned for type AccountsByAccountIDGetForbidden
const AccountsByAccountIDGetForbiddenCode int = 403

/*AccountsByAccountIDGetForbidden Forbidden

swagger:response accountsByAccountIdGetForbidden
*/
type AccountsByAccountIDGetForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.TppMessage `json:"body,omitempty"`
}

// NewAccountsByAccountIDGetForbidden creates AccountsByAccountIDGetForbidden with default headers values
func NewAccountsByAccountIDGetForbidden() *AccountsByAccountIDGetForbidden {

	return &AccountsByAccountIDGetForbidden{}
}

// WithPayload adds the payload to the accounts by account Id get forbidden response
func (o *AccountsByAccountIDGetForbidden) WithPayload(payload *models.TppMessage) *AccountsByAccountIDGetForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the accounts by account Id get forbidden response
func (o *AccountsByAccountIDGetForbidden) SetPayload(payload *models.TppMessage) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AccountsByAccountIDGetForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*AccountsByAccountIDGetDefault Internal Server Error

swagger:response accountsByAccountIdGetDefault
*/
type AccountsByAccountIDGetDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.TppMessage `json:"body,omitempty"`
}

// NewAccountsByAccountIDGetDefault creates AccountsByAccountIDGetDefault with default headers values
func NewAccountsByAccountIDGetDefault(code int) *AccountsByAccountIDGetDefault {
	if code <= 0 {
		code = 500
	}

	return &AccountsByAccountIDGetDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the accounts by account Id get default response
func (o *AccountsByAccountIDGetDefault) WithStatusCode(code int) *AccountsByAccountIDGetDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the accounts by account Id get default response
func (o *AccountsByAccountIDGetDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the accounts by account Id get default response
func (o *AccountsByAccountIDGetDefault) WithPayload(payload *models.TppMessage) *AccountsByAccountIDGetDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the accounts by account Id get default response
func (o *AccountsByAccountIDGetDefault) SetPayload(payload *models.TppMessage) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AccountsByAccountIDGetDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
