// Code generated by go-swagger; DO NOT EDIT.

// /**
//  * OpenPSD PSD2 Server
//  * (C) 2018 by OpenPSD - openpsd.org
//  * Released under the GNU General Public License
//  */

/*
Package restapi OpenPSD PSD2
PSD2 API based on the Berlin Group specs



    Schemes:
      https
    Host: api.openpsd.org
    BasePath: /psd2/v1
    Version: 0.0.1

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
