// Code generated by go-swagger; DO NOT EDIT.

// /**
//  * OpenPSD PSD2 Server
//  * 2018 - OpenPSD - openpsd.org
//  * Released under the GNU General Public License
//  */

package funds

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/openpsd/psd2-server/models"
)

// NewFundsConfirmationsPostParams creates a new FundsConfirmationsPostParams object
// with the default values initialized.
func NewFundsConfirmationsPostParams() *FundsConfirmationsPostParams {
	var ()
	return &FundsConfirmationsPostParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewFundsConfirmationsPostParamsWithTimeout creates a new FundsConfirmationsPostParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewFundsConfirmationsPostParamsWithTimeout(timeout time.Duration) *FundsConfirmationsPostParams {
	var ()
	return &FundsConfirmationsPostParams{

		timeout: timeout,
	}
}

// NewFundsConfirmationsPostParamsWithContext creates a new FundsConfirmationsPostParams object
// with the default values initialized, and the ability to set a context for a request
func NewFundsConfirmationsPostParamsWithContext(ctx context.Context) *FundsConfirmationsPostParams {
	var ()
	return &FundsConfirmationsPostParams{

		Context: ctx,
	}
}

// NewFundsConfirmationsPostParamsWithHTTPClient creates a new FundsConfirmationsPostParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewFundsConfirmationsPostParamsWithHTTPClient(client *http.Client) *FundsConfirmationsPostParams {
	var ()
	return &FundsConfirmationsPostParams{
		HTTPClient: client,
	}
}

/*FundsConfirmationsPostParams contains all the parameters to send to the API endpoint
for the funds confirmations post operation typically these are written to a http.Request
*/
type FundsConfirmationsPostParams struct {

	/*Digest
	  Is contained if and only if the "Signature" element is contained in the header of the request.

	*/
	Digest *string
	/*Signature
	  A signature of the request by the TPP on application level. This might be mandated by ASPSP.

	*/
	Signature *string
	/*TPPSignatureCertificate
	  The certificate used for signing the request, in base64 encoding. It shall be contained if a signature is used, see above.

	*/
	TPPSignatureCertificate *string
	/*XRequestID
	  ID of the request, unique to the call, as determined by the initiating party.

	*/
	XRequestID strfmt.UUID
	/*Body*/
	Body *models.FundsConfirmationsRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the funds confirmations post params
func (o *FundsConfirmationsPostParams) WithTimeout(timeout time.Duration) *FundsConfirmationsPostParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the funds confirmations post params
func (o *FundsConfirmationsPostParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the funds confirmations post params
func (o *FundsConfirmationsPostParams) WithContext(ctx context.Context) *FundsConfirmationsPostParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the funds confirmations post params
func (o *FundsConfirmationsPostParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the funds confirmations post params
func (o *FundsConfirmationsPostParams) WithHTTPClient(client *http.Client) *FundsConfirmationsPostParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the funds confirmations post params
func (o *FundsConfirmationsPostParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDigest adds the digest to the funds confirmations post params
func (o *FundsConfirmationsPostParams) WithDigest(digest *string) *FundsConfirmationsPostParams {
	o.SetDigest(digest)
	return o
}

// SetDigest adds the digest to the funds confirmations post params
func (o *FundsConfirmationsPostParams) SetDigest(digest *string) {
	o.Digest = digest
}

// WithSignature adds the signature to the funds confirmations post params
func (o *FundsConfirmationsPostParams) WithSignature(signature *string) *FundsConfirmationsPostParams {
	o.SetSignature(signature)
	return o
}

// SetSignature adds the signature to the funds confirmations post params
func (o *FundsConfirmationsPostParams) SetSignature(signature *string) {
	o.Signature = signature
}

// WithTPPSignatureCertificate adds the tPPSignatureCertificate to the funds confirmations post params
func (o *FundsConfirmationsPostParams) WithTPPSignatureCertificate(tPPSignatureCertificate *string) *FundsConfirmationsPostParams {
	o.SetTPPSignatureCertificate(tPPSignatureCertificate)
	return o
}

// SetTPPSignatureCertificate adds the tPPSignatureCertificate to the funds confirmations post params
func (o *FundsConfirmationsPostParams) SetTPPSignatureCertificate(tPPSignatureCertificate *string) {
	o.TPPSignatureCertificate = tPPSignatureCertificate
}

// WithXRequestID adds the xRequestID to the funds confirmations post params
func (o *FundsConfirmationsPostParams) WithXRequestID(xRequestID strfmt.UUID) *FundsConfirmationsPostParams {
	o.SetXRequestID(xRequestID)
	return o
}

// SetXRequestID adds the xRequestId to the funds confirmations post params
func (o *FundsConfirmationsPostParams) SetXRequestID(xRequestID strfmt.UUID) {
	o.XRequestID = xRequestID
}

// WithBody adds the body to the funds confirmations post params
func (o *FundsConfirmationsPostParams) WithBody(body *models.FundsConfirmationsRequest) *FundsConfirmationsPostParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the funds confirmations post params
func (o *FundsConfirmationsPostParams) SetBody(body *models.FundsConfirmationsRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *FundsConfirmationsPostParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Digest != nil {

		// header param Digest
		if err := r.SetHeaderParam("Digest", *o.Digest); err != nil {
			return err
		}

	}

	if o.Signature != nil {

		// header param Signature
		if err := r.SetHeaderParam("Signature", *o.Signature); err != nil {
			return err
		}

	}

	if o.TPPSignatureCertificate != nil {

		// header param TPP-Signature-Certificate
		if err := r.SetHeaderParam("TPP-Signature-Certificate", *o.TPPSignatureCertificate); err != nil {
			return err
		}

	}

	// header param X-Request-ID
	if err := r.SetHeaderParam("X-Request-ID", o.XRequestID.String()); err != nil {
		return err
	}

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
