// Code generated by go-swagger; DO NOT EDIT.

// /**
//  * OpenPSD PSD2 Server
//  * (C) 2018 by OpenPSD - openpsd.org
//  * Released under the GNU General Public License
//  */

package payments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PaymentsByPaymentProductPostHandlerFunc turns a function with the right signature into a payments by payment product post handler
type PaymentsByPaymentProductPostHandlerFunc func(PaymentsByPaymentProductPostParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PaymentsByPaymentProductPostHandlerFunc) Handle(params PaymentsByPaymentProductPostParams) middleware.Responder {
	return fn(params)
}

// PaymentsByPaymentProductPostHandler interface for that can handle valid payments by payment product post params
type PaymentsByPaymentProductPostHandler interface {
	Handle(PaymentsByPaymentProductPostParams) middleware.Responder
}

// NewPaymentsByPaymentProductPost creates a new http.Handler for the payments by payment product post operation
func NewPaymentsByPaymentProductPost(ctx *middleware.Context, handler PaymentsByPaymentProductPostHandler) *PaymentsByPaymentProductPost {
	return &PaymentsByPaymentProductPost{Context: ctx, Handler: handler}
}

/*PaymentsByPaymentProductPost swagger:route POST /payments/{payment-product} payments paymentsByPaymentProductPost

create a single payment

Creates a payment initiation resource addressable under {paymentId} with all data relevant for the corresponding payment product. This is the first step in the API to initiate the related payment

*/
type PaymentsByPaymentProductPost struct {
	Context *middleware.Context
	Handler PaymentsByPaymentProductPostHandler
}

func (o *PaymentsByPaymentProductPost) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPaymentsByPaymentProductPostParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
