// Code generated by go-swagger; DO NOT EDIT.

// /**
//  * OpenPSD PSD2 Server
//  * (C) 2018 by OpenPSD - openpsd.org
//  * Released under the GNU General Public License
//  */

package payments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/openpsd/psd2-server/models"
)

// PeriodicPaymentsByPaymentProductPostOKCode is the HTTP code returned for type PeriodicPaymentsByPaymentProductPostOK
const PeriodicPaymentsByPaymentProductPostOKCode int = 200

/*PeriodicPaymentsByPaymentProductPostOK OK

swagger:response periodicPaymentsByPaymentProductPostOK
*/
type PeriodicPaymentsByPaymentProductPostOK struct {

	/*
	  In: Body
	*/
	Payload *models.PeriodicPaymentsResponse `json:"body,omitempty"`
}

// NewPeriodicPaymentsByPaymentProductPostOK creates PeriodicPaymentsByPaymentProductPostOK with default headers values
func NewPeriodicPaymentsByPaymentProductPostOK() *PeriodicPaymentsByPaymentProductPostOK {

	return &PeriodicPaymentsByPaymentProductPostOK{}
}

// WithPayload adds the payload to the periodic payments by payment product post o k response
func (o *PeriodicPaymentsByPaymentProductPostOK) WithPayload(payload *models.PeriodicPaymentsResponse) *PeriodicPaymentsByPaymentProductPostOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the periodic payments by payment product post o k response
func (o *PeriodicPaymentsByPaymentProductPostOK) SetPayload(payload *models.PeriodicPaymentsResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PeriodicPaymentsByPaymentProductPostOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PeriodicPaymentsByPaymentProductPostBadRequestCode is the HTTP code returned for type PeriodicPaymentsByPaymentProductPostBadRequest
const PeriodicPaymentsByPaymentProductPostBadRequestCode int = 400

/*PeriodicPaymentsByPaymentProductPostBadRequest Bad Request

swagger:response periodicPaymentsByPaymentProductPostBadRequest
*/
type PeriodicPaymentsByPaymentProductPostBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.TppMessage `json:"body,omitempty"`
}

// NewPeriodicPaymentsByPaymentProductPostBadRequest creates PeriodicPaymentsByPaymentProductPostBadRequest with default headers values
func NewPeriodicPaymentsByPaymentProductPostBadRequest() *PeriodicPaymentsByPaymentProductPostBadRequest {

	return &PeriodicPaymentsByPaymentProductPostBadRequest{}
}

// WithPayload adds the payload to the periodic payments by payment product post bad request response
func (o *PeriodicPaymentsByPaymentProductPostBadRequest) WithPayload(payload *models.TppMessage) *PeriodicPaymentsByPaymentProductPostBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the periodic payments by payment product post bad request response
func (o *PeriodicPaymentsByPaymentProductPostBadRequest) SetPayload(payload *models.TppMessage) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PeriodicPaymentsByPaymentProductPostBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PeriodicPaymentsByPaymentProductPostUnauthorizedCode is the HTTP code returned for type PeriodicPaymentsByPaymentProductPostUnauthorized
const PeriodicPaymentsByPaymentProductPostUnauthorizedCode int = 401

/*PeriodicPaymentsByPaymentProductPostUnauthorized Unauthorized

swagger:response periodicPaymentsByPaymentProductPostUnauthorized
*/
type PeriodicPaymentsByPaymentProductPostUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.TppMessage `json:"body,omitempty"`
}

// NewPeriodicPaymentsByPaymentProductPostUnauthorized creates PeriodicPaymentsByPaymentProductPostUnauthorized with default headers values
func NewPeriodicPaymentsByPaymentProductPostUnauthorized() *PeriodicPaymentsByPaymentProductPostUnauthorized {

	return &PeriodicPaymentsByPaymentProductPostUnauthorized{}
}

// WithPayload adds the payload to the periodic payments by payment product post unauthorized response
func (o *PeriodicPaymentsByPaymentProductPostUnauthorized) WithPayload(payload *models.TppMessage) *PeriodicPaymentsByPaymentProductPostUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the periodic payments by payment product post unauthorized response
func (o *PeriodicPaymentsByPaymentProductPostUnauthorized) SetPayload(payload *models.TppMessage) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PeriodicPaymentsByPaymentProductPostUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PeriodicPaymentsByPaymentProductPostForbiddenCode is the HTTP code returned for type PeriodicPaymentsByPaymentProductPostForbidden
const PeriodicPaymentsByPaymentProductPostForbiddenCode int = 403

/*PeriodicPaymentsByPaymentProductPostForbidden Forbidden

swagger:response periodicPaymentsByPaymentProductPostForbidden
*/
type PeriodicPaymentsByPaymentProductPostForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.TppMessage `json:"body,omitempty"`
}

// NewPeriodicPaymentsByPaymentProductPostForbidden creates PeriodicPaymentsByPaymentProductPostForbidden with default headers values
func NewPeriodicPaymentsByPaymentProductPostForbidden() *PeriodicPaymentsByPaymentProductPostForbidden {

	return &PeriodicPaymentsByPaymentProductPostForbidden{}
}

// WithPayload adds the payload to the periodic payments by payment product post forbidden response
func (o *PeriodicPaymentsByPaymentProductPostForbidden) WithPayload(payload *models.TppMessage) *PeriodicPaymentsByPaymentProductPostForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the periodic payments by payment product post forbidden response
func (o *PeriodicPaymentsByPaymentProductPostForbidden) SetPayload(payload *models.TppMessage) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PeriodicPaymentsByPaymentProductPostForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*PeriodicPaymentsByPaymentProductPostDefault Internal Server Error

swagger:response periodicPaymentsByPaymentProductPostDefault
*/
type PeriodicPaymentsByPaymentProductPostDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.TppMessage `json:"body,omitempty"`
}

// NewPeriodicPaymentsByPaymentProductPostDefault creates PeriodicPaymentsByPaymentProductPostDefault with default headers values
func NewPeriodicPaymentsByPaymentProductPostDefault(code int) *PeriodicPaymentsByPaymentProductPostDefault {
	if code <= 0 {
		code = 500
	}

	return &PeriodicPaymentsByPaymentProductPostDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the periodic payments by payment product post default response
func (o *PeriodicPaymentsByPaymentProductPostDefault) WithStatusCode(code int) *PeriodicPaymentsByPaymentProductPostDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the periodic payments by payment product post default response
func (o *PeriodicPaymentsByPaymentProductPostDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the periodic payments by payment product post default response
func (o *PeriodicPaymentsByPaymentProductPostDefault) WithPayload(payload *models.TppMessage) *PeriodicPaymentsByPaymentProductPostDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the periodic payments by payment product post default response
func (o *PeriodicPaymentsByPaymentProductPostDefault) SetPayload(payload *models.TppMessage) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PeriodicPaymentsByPaymentProductPostDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
