// Code generated by go-swagger; DO NOT EDIT.

// /**
//  * OpenPSD PSD2 Server
//  * (C) 2018 by OpenPSD - openpsd.org
//  * Released under the GNU General Public License
//  */

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ConsentsStatusResponse Consents Status Response
// swagger:model ConsentsStatusResponse
type ConsentsStatusResponse struct {

	// consent status
	// Required: true
	ConsentStatus ConsentStatus `json:"consentStatus"`

	// This data element is containing information about the status of the SCA method applied. This is free text but might be coded in a future version of the specification.
	ScaStatus string `json:"scaStatus,omitempty"`
}

// Validate validates this consents status response
func (m *ConsentsStatusResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateConsentStatus(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ConsentsStatusResponse) validateConsentStatus(formats strfmt.Registry) error {

	if err := m.ConsentStatus.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("consentStatus")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ConsentsStatusResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ConsentsStatusResponse) UnmarshalBinary(b []byte) error {
	var res ConsentsStatusResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
