// Code generated by go-swagger; DO NOT EDIT.

// /**
//  * OpenPSD PSD2 Server
//  * 2018 - OpenPSD - openpsd.org
//  * Released under the GNU General Public License
//  */

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ConsentsResponse146 Consents Response146
// swagger:model ConsentsResponse146
type ConsentsResponse146 struct {

	// links
	Links map[string]interface{} `json:"_links,omitempty"`

	// challenge data
	ChallengeData *Challenge `json:"challengeData,omitempty"`

	// chosen sca method
	ChosenScaMethod *Authentication `json:"chosenScaMethod,omitempty"`

	// consent status
	ConsentStatus ConsentStatus `json:"consentStatus,omitempty"`

	// Text to be displayed to the PSU
	PsuMessage string `json:"psuMessage,omitempty"`

	// sca methods
	ScaMethods []*Authentication `json:"scaMethods"`

	// transaction status
	TransactionStatus TransactionStatus `json:"transactionStatus,omitempty"`
}

// Validate validates this consents response146
func (m *ConsentsResponse146) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateChallengeData(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateChosenScaMethod(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateConsentStatus(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateScaMethods(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTransactionStatus(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ConsentsResponse146) validateChallengeData(formats strfmt.Registry) error {

	if swag.IsZero(m.ChallengeData) { // not required
		return nil
	}

	if m.ChallengeData != nil {
		if err := m.ChallengeData.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("challengeData")
			}
			return err
		}
	}

	return nil
}

func (m *ConsentsResponse146) validateChosenScaMethod(formats strfmt.Registry) error {

	if swag.IsZero(m.ChosenScaMethod) { // not required
		return nil
	}

	if m.ChosenScaMethod != nil {
		if err := m.ChosenScaMethod.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("chosenScaMethod")
			}
			return err
		}
	}

	return nil
}

func (m *ConsentsResponse146) validateConsentStatus(formats strfmt.Registry) error {

	if swag.IsZero(m.ConsentStatus) { // not required
		return nil
	}

	if err := m.ConsentStatus.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("consentStatus")
		}
		return err
	}

	return nil
}

func (m *ConsentsResponse146) validateScaMethods(formats strfmt.Registry) error {

	if swag.IsZero(m.ScaMethods) { // not required
		return nil
	}

	for i := 0; i < len(m.ScaMethods); i++ {
		if swag.IsZero(m.ScaMethods[i]) { // not required
			continue
		}

		if m.ScaMethods[i] != nil {
			if err := m.ScaMethods[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("scaMethods" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *ConsentsResponse146) validateTransactionStatus(formats strfmt.Registry) error {

	if swag.IsZero(m.TransactionStatus) { // not required
		return nil
	}

	if err := m.TransactionStatus.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("transactionStatus")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ConsentsResponse146) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ConsentsResponse146) UnmarshalBinary(b []byte) error {
	var res ConsentsResponse146
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
