// Code generated by go-swagger; DO NOT EDIT.

// /**
//  * OpenPSD PSD2 Server
//  * 2018 - OpenPSD - openpsd.org
//  * Released under the GNU General Public License
//  */

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// FundsConfirmationsResponse Funds Confirmations Response
// swagger:model FundsConfirmationsResponse
type FundsConfirmationsResponse struct {

	// Equals “true” if sufficient funds are available at the time of the request, “false” otherwise.
	// Required: true
	FundsAvaiable *bool `json:"fundsAvaiable"`
}

// Validate validates this funds confirmations response
func (m *FundsConfirmationsResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateFundsAvaiable(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *FundsConfirmationsResponse) validateFundsAvaiable(formats strfmt.Registry) error {

	if err := validate.Required("fundsAvaiable", "body", m.FundsAvaiable); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *FundsConfirmationsResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *FundsConfirmationsResponse) UnmarshalBinary(b []byte) error {
	var res FundsConfirmationsResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
