// Code generated by go-swagger; DO NOT EDIT.

// /**
//  * OpenPSD PSD2 Server
//  * 2018 - OpenPSD - openpsd.org
//  * Released under the GNU General Public License
//  */

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// Links Links
// swagger:model Links
type Links struct {

	// A link to the resource providing the details of one account
	Account string `json:"account,omitempty"`

	// The link to the payment initiation or consent resource, where the “Transaction Authorization”Request“ is sent to. This is the link to the resource which will authorize the payment or the consent by checking the SCA authentication data within the Embedded SCA approach.
	AuthoriseTransaction string `json:"authoriseTransaction,omitempty"`

	// A link to the resource providing the balance of a dedicated account.
	Balances string `json:"balances,omitempty"`

	// Download link for huge AIS data packages.
	Download string `json:"download,omitempty"`

	// Navigation link for paginated account reports.
	First string `json:"first,omitempty"`

	// Navigation link for paginated account reports.
	Last string `json:"last,omitempty"`

	// Navigation link for paginated account reports.
	Next string `json:"next,omitempty"`

	// Navigation link for paginated account reports.
	Previous string `json:"previous,omitempty"`

	// The link refers to a JSON document specifying the OAuth details of the ASPSP’s authorisation server. JSON document follows the definition given in https://tools.ietf.org/html/draft-ietf-oauth- discovery.
	ScaOAuth string `json:"scaOAuth,omitempty"`

	// A link to an ASPSP site where SCA is performed within the Redirect SCA approach.
	ScaRedirect string `json:"scaRedirect,omitempty"`

	// This is a link to a resource, where the TPP can select the applicable second factor authentication methods for the PSU, if there were several available authentication methods.
	SelectAuthenticationMethod string `json:"selectAuthenticationMethod,omitempty"`

	// The link to the payment initiation resource created by the request itself. This link can be used later to retrieve the transaction status of the payment initiation.
	Self string `json:"self,omitempty"`

	// Status of the resource.
	Status string `json:"status,omitempty"`

	// A link to the resource providing the transaction history of a dediated amount.
	Transactions string `json:"transactions,omitempty"`

	// A link to the resource providing details of a dedicated transaction.
	TransactionsDetails string `json:"transactionsDetails,omitempty"`

	// The link to the payment initiation or account information resource, which needs to be updated by the proprietary data.
	UpdateProprietaryData string `json:"updateProprietaryData,omitempty"`

	// The link to the payment initiation or account information resource, which needs to be updated by a psu password and eventually the psu identification if not delivered yet.
	UpdatePsuAuthentication string `json:"updatePsuAuthentication,omitempty"`

	// The link to the payment initiation or account information resource, which needs to be updated by the psu identification if not delivered yet.
	UpdatePsuIdentification string `json:"updatePsuIdentification,omitempty"`
}

// Validate validates this links
func (m *Links) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Links) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Links) UnmarshalBinary(b []byte) error {
	var res Links
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
