// Code generated by go-swagger; DO NOT EDIT.

// /**
//  * OpenPSD PSD2 Server
//  * 2018 - OpenPSD - openpsd.org
//  * Released under the GNU General Public License
//  */

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

// OtpFormat OtpFormat
// swagger:model OtpFormat
type OtpFormat string

const (

	// OtpFormatCharacters captures enum value "characters"
	OtpFormatCharacters OtpFormat = "characters"

	// OtpFormatInteger captures enum value "integer"
	OtpFormatInteger OtpFormat = "integer"
)

// for schema
var otpFormatEnum []interface{}

func init() {
	var res []OtpFormat
	if err := json.Unmarshal([]byte(`["characters","integer"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		otpFormatEnum = append(otpFormatEnum, v)
	}
}

func (m OtpFormat) validateOtpFormatEnum(path, location string, value OtpFormat) error {
	if err := validate.Enum(path, location, value, otpFormatEnum); err != nil {
		return err
	}
	return nil
}

// Validate validates this otp format
func (m OtpFormat) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateOtpFormatEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
