// Code generated by go-swagger; DO NOT EDIT.

// /**
//  * OpenPSD PSD2 Server
//  * 2018 - OpenPSD - openpsd.org
//  * Released under the GNU General Public License
//  */

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// PaymentidStatusResponse PaymentId Status Response
// swagger:model PaymentidStatusResponse
type PaymentidStatusResponse struct {

	// This data element is containing information about the status of the SCA method applied. This is free text but might be coded in a future version of the specification.
	ScaStatus string `json:"scaStatus,omitempty"`

	// transaction status
	TransactionStatus TransactionStatus `json:"transactionStatus,omitempty"`
}

// Validate validates this paymentid status response
func (m *PaymentidStatusResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateTransactionStatus(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PaymentidStatusResponse) validateTransactionStatus(formats strfmt.Registry) error {

	if swag.IsZero(m.TransactionStatus) { // not required
		return nil
	}

	if err := m.TransactionStatus.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("transactionStatus")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *PaymentidStatusResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PaymentidStatusResponse) UnmarshalBinary(b []byte) error {
	var res PaymentidStatusResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
